apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "netifi-broker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "netifi-broker.name" . }}
    helm.sh/chart: {{ include "netifi-broker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources:
      - endpoints
    verbs: ["get"]