---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netifi-broker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "netifi-broker.name" . }}
    helm.sh/chart: {{ include "netifi-broker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "netifi-broker.name" . }}
      helm.sh/chart: {{ include "netifi-broker.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "netifi-broker.name" . }}
        helm.sh/chart: {{ include "netifi-broker.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ include "netifi-broker.fullname" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - {{ include "netifi-broker.name" . }}
                    - key: "app.kubernetes.io/instance"
                      operator: In
                      values:
                        - {{ .Release.Name }}
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ include "netifi-broker.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            - name: cluster
              containerPort: {{ .Values.cluster.port }}
            - name: tcp
              containerPort: {{ .Values.tcp.port }}
            - name: websocket
              containerPort: {{ .Values.websocket.port }}
            - name: admin
              containerPort: {{ .Values.admin.port }}
            - name: console
              containerPort: {{ .Values.console.port }}
          env:
            - name: AUTHENTICATION.0.accessKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "netifi-broker.fullname" . }}-adminseedtoken
                  key: adminAccessKey
            - name: AUTHENTICATION.0.accessToken
              valueFrom:
                secretKeyRef:
                  name: {{ include "netifi-broker.fullname" . }}-adminseedtoken
                  key: adminAccessToken
            - name: ADMIN_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "netifi-broker.fullname" . }}-adminseedtoken
                  key: adminAccessKey
            - name: ADMIN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "netifi-broker.fullname" . }}-adminseedtoken
                  key: adminAccessToken
            - name: BROKER_PUBLIC_ADDRESS
              {{- if .Values.tcp.public.addressUsePodIP }}
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
              {{- else }}
              value: "{{ .Values.tcp.public.address }}"
              {{- end }}
            - name: BROKER_PUBLIC_PORT
              value: "{{ .Values.tcp.public.port }}"
            - name: WEBSOCKET_BROKER_PUBLIC_ADDRESS
              {{- if .Values.websocket.public.addressUsePodIP }}
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
                {{- else }}
              value: "{{ .Values.websocket.public.address }}"
              {{- end }}
            - name: WEBSOCKET_BROKER_PUBLIC_PORT
              value: "{{ .Values.websocket.public.port }}"
            - name: ADMIN_PUBLIC_ADDRESS
              {{- if .Values.admin.public.addressUsePodIP }}
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
              {{- else }}
              value: "{{ .Values.admin.public.address }}"
              {{- end }}
            - name: CLUSTER_PUBLIC_ADDRESS
              {{- if .Values.cluster.public.addressUsePodIP }}
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
              {{- else }}
              value: "{{ .Values.cluster.public.address }}"
              {{- end }}
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_DEPLOYMENT_NAME
              value: {{ include "netifi-broker.fullname" . }}
            - name: KUBERNETES_PORT_NAME
              value: "cluster"
            - name: ENVIRONMENT
              value: {{ (gt .Values.replicaCount 1.0) | ternary "kubernetes" "local" }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}