apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netifi-broker.fullname" . }}-adminseedtoken
  labels:
    app.kubernetes.io/name: {{ include "netifi-broker.name" . }}
    helm.sh/chart: {{ include "netifi-broker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  adminAccessKey:  {{ .Values.admin.accessKey | b64enc | quote }}
  adminAccessToken: {{ .Values.admin.accessToken | b64enc | quote }}
