apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netifi-broker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "netifi-broker.name" . }}
    helm.sh/chart: {{ include "netifi-broker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}